# Generated by Django 5.1.3 on 2025-02-23 09:34

import django.contrib.postgres.fields
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location_lat", models.DecimalField(decimal_places=10, max_digits=20)),
                (
                    "location_long",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ادرس شعب",
                "verbose_name_plural": "ادرس شعب ها",
                "db_table": "business_address",
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(
                        max_length=150, verbose_name="نام و نام خوانوادگی"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=11,
                        validators=[users.validators.MobileValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیح")),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "تماس با ما",
                "db_table": "contact_us",
            },
        ),
        migrations.CreateModel(
            name="ContactUsSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("social_link", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "شبکه اجتماعی",
                "verbose_name_plural": "شبکه های اجتماعی",
                "db_table": "social",
            },
        ),
        migrations.CreateModel(
            name="HeaderSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "هدر سایت",
                "verbose_name_plural": "هدر سایت",
                "db_table": "header_site",
            },
        ),
        migrations.CreateModel(
            name="HomeSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "site_logo",
                    models.ImageField(
                        upload_to="main_settings/home-site/%Y/%m/%d",
                        verbose_name="عکس لوگو سایت",
                    ),
                ),
                (
                    "home_site_image",
                    models.ImageField(
                        upload_to="main_settings/home_site_image/%Y/%m/%d"
                    ),
                ),
                ("home_site_title", models.CharField(max_length=50)),
                ("home_site_description", models.CharField(max_length=500)),
                ("about_us_energy_title", models.CharField(max_length=50)),
                ("about_us_energy_body", models.CharField(max_length=500)),
                (
                    "about_us_energy_image",
                    models.ImageField(
                        upload_to="main_settings/about_us_energy_image/%Y/%m/%d"
                    ),
                ),
                (
                    "energy_image",
                    models.ImageField(upload_to="main_settings/energy_image/%Y/%m/%d"),
                ),
                (
                    "office_contact_number",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=15), size=None
                    ),
                ),
                (
                    "office_email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254), size=None
                    ),
                ),
                ("description_of_our_group", models.CharField(max_length=600)),
                ("is_main_settings", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "بخش هایی از سایت",
                "verbose_name_plural": "بخش های از سایت",
                "db_table": "home_site",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
            ],
            options={
                "verbose_name": "خبرنامه",
                "verbose_name_plural": "خبرنامه",
                "db_table": "newsletter",
            },
        ),
        migrations.CreateModel(
            name="TopRankProfessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="نام و نام خوانوادگی"),
                ),
                (
                    "field_title",
                    models.CharField(max_length=50, verbose_name="عنوان درس"),
                ),
                (
                    "professor_image",
                    models.ImageField(
                        upload_to="main_settings/top_professor/%Y/%m/%d",
                        verbose_name="عکس اساتید",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "برترین اساتید",
                "verbose_name_plural": "برترین اساتید",
                "db_table": "top_rank_professor",
            },
        ),
    ]
