# Generated by Django 5.1.1 on 2024-10-19 20:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.TextField(verbose_name="ادرس")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="لوکیشن"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال بودن"),
                ),
            ],
            options={
                "verbose_name": "ادرس شعب",
                "verbose_name_plural": "ادرس شعب ها",
                "db_table": "business_address",
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(
                        max_length=150, verbose_name="نام و نام خوانوادگی"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        max_length=11,
                        validators=[users.validators.MobileValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیح")),
            ],
            options={
                "verbose_name": "ارتباط با ما",
                "verbose_name_plural": "ارتباط با ما",
                "db_table": "contact_us",
            },
        ),
        migrations.CreateModel(
            name="HeaderSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "هدر سایت",
                "verbose_name_plural": "هدر سایت",
                "db_table": "header_site",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
            ],
            options={
                "verbose_name": "خبرنامه",
                "verbose_name_plural": "خبرنامه",
                "db_table": "newsletter",
            },
        ),
        migrations.CreateModel(
            name="TopRankStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="نام خوانوادگی"),
                ),
                ("fields", models.CharField(max_length=50, verbose_name="عنوان شغلی")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال بودن"),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("experimental", "تجربی"),
                            ("math", "ریاضی"),
                            ("human", "انسانی"),
                        ],
                        max_length=12,
                        verbose_name="title",
                    ),
                ),
            ],
            options={
                "verbose_name": "برترین دانشجویان",
                "verbose_name_plural": "برترین دانشجویان",
                "db_table": "top_rank",
            },
        ),
        migrations.CreateModel(
            name="HomeSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "header_phone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="شماره تماس"
                    ),
                ),
                ("about_us_body", models.TextField(verbose_name="متن درباره ما")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="ایمیل"
                    ),
                ),
                ("description_footer", models.TextField(verbose_name="توضیح فوتر")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال باشد"),
                ),
                (
                    "about_us_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_site_about_us_image",
                        to="images.image",
                    ),
                ),
                (
                    "awards_image",
                    models.ManyToManyField(
                        related_name="home_site_awards_image",
                        to="images.image",
                        verbose_name="عکس جوایز و افتخارات",
                    ),
                ),
                (
                    "site_logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_site_logo",
                        to="images.image",
                        verbose_name="عکس لوگو سایت",
                    ),
                ),
                (
                    "slider_image",
                    models.ManyToManyField(
                        related_name="home_site_slider",
                        to="images.image",
                        verbose_name="عکس اسلایدر سایت",
                    ),
                ),
                (
                    "slider_professor_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_site_slider_professor_image",
                        to="images.image",
                        verbose_name="عکس اساتید",
                    ),
                ),
                (
                    "team_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_site_team_image",
                        to="images.image",
                        verbose_name="عکس تیم",
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش هایی از سایت",
                "verbose_name_plural": "بخش های از سایت",
                "db_table": "home_site",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="عنوان خدمات ما"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات خدمات ما "
                    ),
                ),
                ("link", models.URLField(verbose_name="ادرس")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="قعال باشد"),
                ),
                (
                    "services_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services_image",
                        to="images.image",
                        verbose_name="عکس یا لوگوی خدمات ما",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمات",
                "verbose_name_plural": "خدمات",
                "db_table": "services",
            },
        ),
        migrations.CreateModel(
            name="TopRankProfessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="نام و نام خوانوادگی"),
                ),
                (
                    "field_title",
                    models.CharField(max_length=50, verbose_name="عنوان درس"),
                ),
                (
                    "professor_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="top_rank_professor_image",
                        to="images.image",
                        verbose_name="عکس استاد",
                    ),
                ),
            ],
            options={
                "verbose_name": "برترین اساتید",
                "verbose_name_plural": "برترین اساتید",
                "db_table": "top_rank_professo r",
            },
        ),
    ]
