# Generated by Django 5.1.1 on 2024-10-30 07:26

import main_settings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("main_settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homesite",
            name="about_us_image",
        ),
        migrations.AlterField(
            model_name="homesite",
            name="header_phone_number",
            field=models.CharField(
                help_text="شماره تماس میتواند 11 رقمی تا 15 رقمی باشد",
                max_length=15,
                unique=True,
                validators=[main_settings.validators.HomeMobileValidator()],
                verbose_name="شماره تماس",
            ),
        ),
        migrations.RemoveField(
            model_name="homesite",
            name="slider_professor_image",
        ),
        migrations.RemoveField(
            model_name="homesite",
            name="team_image",
        ),
        migrations.AddField(
            model_name="homesite",
            name="about_us_image",
            field=models.ManyToManyField(
                related_name="home_site_about_us_image", to="images.image"
            ),
        ),
        migrations.AddField(
            model_name="homesite",
            name="slider_professor_image",
            field=models.ManyToManyField(
                related_name="home_site_slider_professor_image",
                to="images.image",
                verbose_name="عکس اساتید",
            ),
        ),
        migrations.AddField(
            model_name="homesite",
            name="team_image",
            field=models.ManyToManyField(
                related_name="home_site_team_image",
                to="images.image",
                verbose_name="عکس تیم",
            ),
        ),
    ]
