# Generated by Django 5.1.1 on 2024-10-06 14:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("main_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.TextField(verbose_name="ادرس")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="لوکیشن"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال بودن"),
                ),
            ],
            options={
                "verbose_name": "business address",
                "verbose_name_plural": "business address",
                "db_table": "business_address",
            },
        ),
        migrations.RemoveField(
            model_name="awards",
            name="awards_image",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="footer_address",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="footer_logo",
        ),
        migrations.RemoveField(
            model_name="footersocial",
            name="footer",
        ),
        migrations.RemoveField(
            model_name="sitelogo",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="slider",
            name="slider_image",
        ),
        migrations.RemoveField(
            model_name="sliderprofessorimages",
            name="professor_image",
        ),
        migrations.AddField(
            model_name="services",
            name="description",
            field=models.TextField(default=0, verbose_name="توضیحات خدمات ما "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="services",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="قعال باشد"),
        ),
        migrations.AlterField(
            model_name="services",
            name="services_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services_image",
                to="images.image",
                verbose_name="عکس یا لوگوی خدمات ما",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="title",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="عنوان خدمات ما"
            ),
        ),
        migrations.CreateModel(
            name="HomeSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "header_phone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="شماره تماس"
                    ),
                ),
                ("about_us_body", models.TextField(verbose_name="متن درباره ما")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="ایمیل"
                    ),
                ),
                ("description_footer", models.TextField(verbose_name="توضحی")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال باشد"),
                ),
                (
                    "about_us_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_site_about_us_image",
                        to="images.image",
                    ),
                ),
                (
                    "awards_image",
                    models.ManyToManyField(
                        related_name="home_site_awards_image",
                        to="images.image",
                        verbose_name="عکس جوایز و افتخارات",
                    ),
                ),
                (
                    "site_logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_site_logo",
                        to="images.image",
                        verbose_name="عکس لوگو سایت",
                    ),
                ),
                (
                    "slider_image",
                    models.ManyToManyField(
                        related_name="home_site_slider",
                        to="images.image",
                        verbose_name="عکس اسلایدر سایت",
                    ),
                ),
                (
                    "slider_professor_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_site_slider_professor_image",
                        to="images.image",
                        verbose_name="عکس اساتید",
                    ),
                ),
                (
                    "team_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_site_team_image",
                        to="images.image",
                        verbose_name="عکس تیم",
                    ),
                ),
            ],
            options={
                "verbose_name": "home site",
                "verbose_name_plural": "home sites",
                "db_table": "home_site",
            },
        ),
        migrations.CreateModel(
            name="TopRankProfessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="نام و نام خوانوادگی"),
                ),
                (
                    "field_title",
                    models.CharField(max_length=50, verbose_name="عنوان درس"),
                ),
                (
                    "professor_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="top_rank_professor_image",
                        to="images.image",
                        verbose_name="عکس استاد",
                    ),
                ),
            ],
            options={
                "verbose_name": "top rank professor",
                "verbose_name_plural": "top rank professors",
                "db_table": "top_rank_professo r",
            },
        ),
        migrations.DeleteModel(
            name="AboutUs",
        ),
        migrations.DeleteModel(
            name="Awards",
        ),
        migrations.DeleteModel(
            name="FooterAddress",
        ),
        migrations.DeleteModel(
            name="Footer",
        ),
        migrations.DeleteModel(
            name="FooterSocial",
        ),
        migrations.DeleteModel(
            name="SiteLogo",
        ),
        migrations.DeleteModel(
            name="Slider",
        ),
        migrations.DeleteModel(
            name="SliderProfessorImages",
        ),
    ]
