# Generated by Django 5.0.8 on 2024-09-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="toprank",
            name="fields",
            field=models.CharField(default=0, max_length=50, verbose_name="fields"),
            preserve_default=False,
        ),
    ]
