# Generated by Django 5.1.3 on 2025-02-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="contactus",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
