# Generated by Django 5.1.1 on 2024-11-09 18:33

import main_settings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "تماس با ما", "verbose_name_plural": "تماس با ما"},
        ),
        migrations.RemoveField(
            model_name="businessaddress",
            name="location",
        ),
        migrations.RemoveField(
            model_name="homesite",
            name="about_us_image",
        ),
        migrations.AddField(
            model_name="businessaddress",
            name="location_lat",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessaddress",
            name="location_long",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homesite",
            name="header_phone_number",
            field=models.CharField(
                help_text="شماره تماس میتواند 11 رقمی تا 15 رقمی باشد",
                max_length=15,
                unique=True,
                validators=[main_settings.validators.HomeMobileValidator()],
                verbose_name="شماره تماس هدر",
            ),
        ),
    ]
