# Generated by Django 5.1.3 on 2025-02-23 10:38

import shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0002_contactus_deleted_at_contactus_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homesite",
            name="about_us_energy_image",
            field=models.ImageField(
                upload_to="main_settings/about_us_energy_image/%Y/%m/%d",
                validators=[shop.utils.image_upload_validator],
            ),
        ),
        migrations.AlterField(
            model_name="homesite",
            name="energy_image",
            field=models.ImageField(
                upload_to="main_settings/energy_image/%Y/%m/%d",
                validators=[shop.utils.image_upload_validator],
            ),
        ),
        migrations.AlterField(
            model_name="homesite",
            name="home_site_image",
            field=models.ImageField(
                upload_to="main_settings/home_site_image/%Y/%m/%d",
                validators=[shop.utils.image_upload_validator],
            ),
        ),
    ]
