# Generated by Django 5.1.1 on 2024-10-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0002_businessaddress_remove_awards_awards_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toprankstudent",
            name="slug",
        ),
        migrations.AlterField(
            model_name="homesite",
            name="description_footer",
            field=models.TextField(verbose_name="توضیح فوتر"),
        ),
    ]
