# Generated by Django 5.0.8 on 2024-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0003_alter_toprank_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="footer_address",
        ),
        migrations.AlterField(
            model_name="toprank",
            name="title",
            field=models.CharField(
                choices=[
                    ("experimental", "تجربی"),
                    ("math", "ریاضی"),
                    ("human", "انسانی"),
                ],
                max_length=12,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="footer",
            name="footer_address",
            field=models.ManyToManyField(
                related_name="footer_address", to="main_settings.footeraddress"
            ),
        ),
    ]
