# Generated by Django 5.1.3 on 2025-02-23 10:53

import shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0003_alter_homesite_about_us_energy_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homesite",
            name="about_us_energy_image",
        ),
        migrations.RemoveField(
            model_name="homesite",
            name="home_site_image",
        ),
        migrations.AddField(
            model_name="homesite",
            name="home_about_section_banner",
            field=models.ImageField(
                null=True,
                upload_to="main_settings/about_us_energy_image/",
                validators=[shop.utils.image_upload_validator],
            ),
        ),
        migrations.AddField(
            model_name="homesite",
            name="home_hero_section_image",
            field=models.ImageField(
                null=True,
                upload_to="main_settings/home_hero_section_image/",
                validators=[shop.utils.image_upload_validator],
            ),
        ),
        migrations.AddField(
            model_name="homesite",
            name="home_middle_page_banner",
            field=models.ImageField(
                null=True,
                upload_to="main_settings/home_middle_page_banner/",
                validators=[shop.utils.image_upload_validator],
            ),
        ),
        migrations.AlterField(
            model_name="homesite",
            name="site_logo",
            field=models.ImageField(
                upload_to="main_settings/home-site/", verbose_name="عکس لوگو سایت"
            ),
        ),
    ]
