# Generated by Django 5.1.1 on 2024-10-06 15:38

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0003_remove_toprankstudent_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessaddress",
            options={"verbose_name": "ادرس شعب", "verbose_name_plural": "ادرس شعب ها"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={
                "verbose_name": "ارتباط با ما",
                "verbose_name_plural": "ارتباط با ما",
            },
        ),
        migrations.AlterModelOptions(
            name="headersite",
            options={"verbose_name": "هدر سایت", "verbose_name_plural": "هدر سایت"},
        ),
        migrations.AlterModelOptions(
            name="homesite",
            options={
                "verbose_name": "بخش هایی از سایت",
                "verbose_name_plural": "بخش های از سایت",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={"verbose_name": "خبرنامه", "verbose_name_plural": "خبرنامه"},
        ),
        migrations.AlterModelOptions(
            name="services",
            options={"verbose_name": "خدمات", "verbose_name_plural": "خدمات"},
        ),
        migrations.AlterModelOptions(
            name="toprankprofessor",
            options={
                "verbose_name": "برترین اساتید",
                "verbose_name_plural": "برترین اساتید",
            },
        ),
        migrations.AlterModelOptions(
            name="toprankstudent",
            options={
                "verbose_name": "برترین دانشجویان",
                "verbose_name_plural": "برترین دانشجویان",
            },
        ),
        migrations.AddField(
            model_name="services",
            name="link",
            field=models.URLField(default=0, verbose_name="ادرس"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactus",
            name="description",
            field=models.TextField(verbose_name="توضیح"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="full_name",
            field=models.CharField(max_length=150, verbose_name="نام و نام خوانوادگی"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="mobile_phone",
            field=models.CharField(
                max_length=11,
                validators=[users.validators.MobileValidator()],
                verbose_name="شماره موبایل",
            ),
        ),
        migrations.AlterField(
            model_name="toprankstudent",
            name="fields",
            field=models.CharField(max_length=50, verbose_name="عنوان شغلی"),
        ),
        migrations.AlterField(
            model_name="toprankstudent",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="toprankstudent",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال بودن"),
        ),
        migrations.AlterField(
            model_name="toprankstudent",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="نام خوانوادگی"),
        ),
    ]
