# Generated by Django 5.1.1 on 2024-10-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0004_alter_businessaddress_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="توضیحات خدمات ما "
            ),
        ),
    ]
