# Generated by Django 5.0.8 on 2024-09-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_settings",
            "0004_remove_footer_footer_address_alter_toprank_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="footersocial",
            name="footer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_social",
                to="main_settings.footer",
            ),
            preserve_default=False,
        ),
    ]
