# Generated by Django 5.1.3 on 2025-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0004_remove_homesite_about_us_energy_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homesite",
            name="footer_logo",
            field=models.ImageField(
                null=True,
                upload_to="main_settings/footer_logo/",
                verbose_name="عکس لوگو فوتر سایت",
            ),
        ),
        migrations.AlterField(
            model_name="homesite",
            name="site_logo",
            field=models.ImageField(
                upload_to="main_settings/header_logo/", verbose_name="عکس لوگو سایت"
            ),
        ),
    ]
