# Generated by Django 5.0.8 on 2024-09-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0005_footersocial_footer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footersocial",
            name="social_url",
            field=models.URLField(verbose_name="footer url"),
        ),
    ]
