# Generated by Django 5.1.3 on 2025-02-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0005_homesite_footer_logo_alter_homesite_site_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homesite",
            old_name="about_us_energy_body",
            new_name="home_about_section_body",
        ),
        migrations.RenameField(
            model_name="homesite",
            old_name="about_us_energy_title",
            new_name="home_about_section_title",
        ),
    ]
