# Generated by Django 5.1.3 on 2025-02-23 11:11

import shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_settings",
            "0006_rename_about_us_energy_body_homesite_home_about_section_body_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homesite",
            name="energy_image",
        ),
        migrations.AlterField(
            model_name="homesite",
            name="home_about_section_banner",
            field=models.ImageField(
                null=True,
                upload_to="main_settings/home_about_section_banner/",
                validators=[shop.utils.image_upload_validator],
            ),
        ),
    ]
