# Generated by Django 5.1.3 on 2025-02-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0007_remove_homesite_energy_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homesite",
            options={"verbose_name": "صفحه اصلی", "verbose_name_plural": "صفحه اصلی"},
        ),
        migrations.RenameField(
            model_name="homesite",
            old_name="home_site_description",
            new_name="home_hero_section_description",
        ),
        migrations.RenameField(
            model_name="homesite",
            old_name="home_site_title",
            new_name="home_hero_section_title",
        ),
    ]
