# Generated by Django 5.0.8 on 2024-09-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0007_rename_professorimages_sliderprofessorimages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
