# Generated by Django 5.1.3 on 2025-02-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0008_alter_homesite_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactussocial",
            name="social_name",
            field=models.CharField(
                help_text="نام شکبه اجتماعی", max_length=50, null=True
            ),
        ),
    ]
