# Generated by Django 5.1.3 on 2025-02-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_settings", "0009_contactussocial_social_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactussocial",
            name="social_link",
            field=models.CharField(help_text="ادرس شبکه اجتماعی", max_length=50),
        ),
    ]
