# Generated by Django 5.1.1 on 2024-10-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(max_length=20, unique=True)),
                ("final_price", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("license_key", models.TextField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_payment",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "payments",
                "verbose_name_plural": "payments",
                "db_table": "payments",
            },
        ),
    ]
