# Generated by Django 5.1.1 on 2024-11-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="discount_value",
        ),
    ]
