# Generated by Django 5.1.3 on 2024-11-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order_number",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
