# Generated by Django 5.1.1 on 2024-11-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "پرداخت", "verbose_name_plural": "پرداخت ها"},
        ),
    ]
