# Generated by Django 5.1.3 on 2024-11-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
