# Generated by Django 5.1.3 on 2024-11-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order_number",
        ),
    ]
