# Generated by Django 5.0.8 on 2024-08-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="useraccount",
            managers=[],
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="user_id",
            new_name="user",
        ),
    ]
