# Generated by Django 5.1.1 on 2024-11-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="gpa",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="major",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
