# Generated by Django 5.0.8 on 2024-09-18 21:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="last_login",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
