# Generated by Django 5.1.3 on 2025-02-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userinfo",
            name="unique_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="bio",
            field=models.CharField(
                blank=True, help_text="درباره خودت", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="birth_date",
            field=models.DateField(blank=True, help_text="تاریخ تولد", null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="user_info_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_info_image",
                to="images.image",
            ),
        ),
        migrations.AlterField(
            model_name="gradegpa",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "is_verified": True},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_grade_gpas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="ایمیل"
            ),
        ),
    ]
