# Generated by Django 5.0.8 on 2024-09-13 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 13, 12, 24, 27, 636075, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
