# Generated by Django 5.1.1 on 2024-10-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "کد",
                "verbose_name_plural": "کدها",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربر ها",
            },
        ),
        migrations.AlterModelOptions(
            name="userinfo",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "پروفایل کاربر",
                "verbose_name_plural": "پروفایل کاربرها",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
