# Generated by Django 5.1.1 on 2024-10-07 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="request_user",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
