# Generated by Django 5.0.8 on 2024-09-13 12:26

import datetime
import users.random_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_otp_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code",
            field=models.CharField(
                default=users.random_code.generate_random_code,
                max_length=12,
                unique=True,
                verbose_name="OTP code",
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 13, 12, 28, 25, 801077, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
