# Generated by Django 5.0.8 on 2024-09-19 10:47

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_useraccount_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2024, 9, 19, 10, 51, 37, 903999, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="date_joined",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2024, 9, 19, 10, 51, 37, 905013, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2024, 9, 19, 10, 51, 37, 903999, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
