# Generated by Django 5.0.8 on 2024-08-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_useraccount_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={},
        ),
    ]
