# Generated by Django 5.1.1 on 2024-10-10 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_otp_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="gpa",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="معدل",
            ),
        ),
    ]
