# Generated by Django 5.0.8 on 2024-09-07 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userinfo_is_active_alter_otp_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="otp",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 9, 5, 59, 168047, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
