# Generated by Django 5.1.1 on 2024-10-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userinfo_major_alter_userinfo_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gradegpa",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade_name",
            field=models.CharField(max_length=30, unique=True, verbose_name="نام پایه"),
        ),
    ]
