# Generated by Django 5.0.8 on 2024-09-09 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_otp_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 9, 12, 9, 4, 525010, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
