# Generated by Django 5.1.3 on 2025-02-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userinfo_unique_email_remove_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="کاربر احراز شده"),
        ),
    ]
