# Generated by Django 5.0.8 on 2024-09-07 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userinfo_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 12, 26, 1, 255014, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
