# Generated by Django 5.0.8 on 2024-09-20 06:30

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_otp_created_at_alter_useraccount_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="date_joined",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2024, 9, 20, 6, 34, 41, 922715, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
