# Generated by Django 5.0.8 on 2024-09-01 11:33

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userinfo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveIntegerField(default=165640894)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "send code",
                "verbose_name_plural": "send codes",
                "db_table": "send_code",
            },
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="mobile_phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[users.validators.MobileValidator()],
                verbose_name="mobile phone",
            ),
        ),
        migrations.DeleteModel(
            name="PasswordOtp",
        ),
    ]
