# Generated by Django 5.1.1 on 2024-11-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="is_deleted",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
