# Generated by Django 5.1.3 on 2025-02-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={"verbose_name": "کد otp", "verbose_name_plural": "کدهای otp"},
        ),
        migrations.AddField(
            model_name="otp",
            name="user_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
