# Generated by Django 5.0.8 on 2024-09-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_sendcode_alter_useraccount_mobile_phone_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SendCode",
        ),
    ]
