# Generated by Django 5.1.1 on 2024-10-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userinfo_gpa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="request_user",
        ),
    ]
