# Generated by Django 5.0.8 on 2024-09-20 08:23

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_otp_created_at_alter_useraccount_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="date_joined",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2024, 9, 20, 8, 27, 26, 28479, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
    ]
