# Generated by Django 5.0.8 on 2024-09-10 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_otp_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 10, 13, 29, 2, 778554, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
