# Generated by Django 5.0.8 on 2024-09-01 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_sendcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 1, 12, 6, 6, 218732, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
