# Generated by Django 5.0.8 on 2024-09-20 09:05

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_useraccount_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="date_joined",
            field=django_jalali.db.models.jDateTimeField(
                default=datetime.datetime(
                    2024, 9, 20, 9, 9, 55, 561092, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
    ]
