# Generated by Django 5.1.1 on 2024-10-23 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_gradegpa_options_alter_gradegpa_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradegpa",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grade_gpa",
                to="users.grade",
                verbose_name="پایه",
            ),
        ),
    ]
