# Generated by Django 5.1.1 on 2024-10-15 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_otp_request_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeGpa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("دهم", "دهم"),
                            ("یازدهم", "یازدهم"),
                            ("دوازدهم", "دوازدهم"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="معدل",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_gpas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "grade gpa",
                "verbose_name_plural": "grade gpa",
                "db_table": "grade_gpa",
                "unique_together": {("user", "grade")},
            },
        ),
    ]
