services:
  django_app:
    build: .
    depends_on:
      - postgres
    container_name: django_app
    restart: always
    networks:
      - main
    volumes:
      - ./static/:/home/app/static
      - ./media/:/home/app/media
    command: >
      sh -c "python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput&&
            python manage.py createsuperuser --mobile_phone 09391640664 --email m.goodarzi606@gmail.com --noinput;
            python manage.py collectstatic --noinput
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

  postgres:
    container_name: postgres_db
    image: postgres:16.4-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - main

  nginx:
    container_name: nginx
    restart: on_failure
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    

networks:
  main:

volumes:
  nginx:

