services:
  django_app:
    build: .
    container_name: django_app
    restart: always
    networks:
      - main
  
  postgres:
    container_name: postgres_db
    image: postgres:16.4-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - main
