services:
  django_app:
    build:
      context: .
    depends_on:
      - postgres
    container_name: django_app
    restart: always
    ports:
      - "8002:8000"
    networks:
      - main
    volumes:
      - .:/home/app
      - djangp-static:/home/app/static
      - supervisor:/etc/supervisor/conf.d
    # command: >
    #   sh -c "python manage.py makemigrations --noinput &&
    #   python manage.py migrate --noinput &&
    #   python manage.py createsuperuser --mobile_phone 09391640664 --email m.goodarzi606@gmail.com --noinput"

    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_DB}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

  postgres:
    container_name: postgres_db
    image: postgres:16.4-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    networks:
      - main
    volumes:
      - azadi-data:/var/lib/postgresql/data

  redis:
    container_name: radis
    image: redis:7.4-alpine
    restart: always
    expose:
      - "6379"
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}

networks:
  main:

volumes:
  djangp-static:
  azadi-data:
  supervisor:
#  nginx:
