services:
  django_app:
    build:
      context: .
    container_name: django_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - main
    volumes:
      - .:/home/app
      - supervisor:/etc/supervisor
#    command: sh -c "python manage.py makemigrations && \
#      python manage.py migrate && \
#      python manage.py collectstatic --noinput"

    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${DEPLOY_SECRET_KEY}
      - LIARA_ENDPOINT=${LIARA_ENDPOINT}
      - LIARA_BUCKET_NAME=${LIARA_BUCKET_NAME}
      - LIARA_ACCESS_KEY=${LIARA_ACCESS_KEY}
      - LIARA_SECRET_KEY=${LIARA_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - LIARA_REDIS_URL=${LIARA_REDIS_URL}


networks:
  main:

volumes:
  django-static:
  supervisor:
