# Generated by Django 5.0.8 on 2024-09-13 12:16

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="contact name"),
                ),
                (
                    "contact_mobile",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="contact mobile",
                    ),
                ),
                (
                    "contact_url",
                    models.URLField(blank=True, null=True, verbose_name="contact url"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "professor contact",
                "verbose_name_plural": "professor contacts",
                "db_table": "professor_contact",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="last_name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "nation_code",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="nation code"
                    ),
                ),
                (
                    "birth_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="birth date"
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(max_length=255, verbose_name="field of study"),
                ),
                (
                    "name_of_education",
                    models.CharField(max_length=255, verbose_name="name of education"),
                ),
                (
                    "education_status",
                    models.CharField(
                        choices=[
                            ("دیپلم", "دیپلم"),
                            ("فارغ التحصیل کاردانی", "فارغ التحصیل کاردانی"),
                            ("دانشجوی کارشناسی", "دانشجوی کارشناسی"),
                            ("فارغ التحصیل کارشناسی", "فارغ التحصیل کارشناسی"),
                            ("دانشجوی کارشناسی ارشد", "دانشجوی کارشناسی ارشد"),
                            (
                                "فارغ التحصیل کارشناسی ارشد",
                                "فارغ التحصیل کارشناسی ارشد",
                            ),
                            ("دانشجوی دکترا", "دانشجوی دکترا"),
                            ("فارغ التحصیل دکترا", "فارغ التحصیل دکترا"),
                        ],
                        max_length=26,
                        verbose_name="education status",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate_image",
                        to="images.image",
                    ),
                ),
                (
                    "professor_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professor_image",
                        to="images.image",
                    ),
                ),
                (
                    "professor_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact",
                        to="professors.professorcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "professor",
                "verbose_name_plural": "professors",
                "db_table": "professors",
            },
        ),
    ]
