# Generated by Django 5.1.1 on 2024-11-01 15:24

import django.contrib.postgres.fields
import django.db.models.deletion
import professors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="نام خانوادگی"),
                ),
                (
                    "nation_code",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[professors.validators.NationCodeValidator()],
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "field_of_study",
                    models.CharField(max_length=255, verbose_name="رشته تحصیلی"),
                ),
                (
                    "name_of_education",
                    models.CharField(max_length=255, verbose_name="نام دانشگاه"),
                ),
                (
                    "education_status",
                    models.CharField(
                        choices=[
                            ("دیپلم", "دیپلم"),
                            ("فارغ التحصیل کاردانی", "فارغ التحصیل کاردانی"),
                            ("دانشجوی کارشناسی", "دانشجوی کارشناسی"),
                            ("فارغ التحصیل کارشناسی", "فارغ التحصیل کارشناسی"),
                            ("دانشجوی کارشناسی ارشد", "دانشجوی کارشناسی ارشد"),
                            (
                                "فارغ التحصیل کارشناسی ارشد",
                                "فارغ التحصیل کارشناسی ارشد",
                            ),
                            ("دانشجوی دکترا", "دانشجوی دکترا"),
                            ("فارغ التحصیل دکترا", "فارغ التحصیل دکترا"),
                        ],
                        max_length=26,
                        verbose_name="وضعیت تحصیل",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "mobile_phone",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=11, verbose_name="شماره تلفن های استاد"
                        ),
                        blank=True,
                        null=True,
                        size=5,
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate_image",
                        to="images.image",
                        verbose_name="عکس اخرین مدرک تحصیلی",
                    ),
                ),
                (
                    "professor_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professor_image",
                        to="images.image",
                        verbose_name="عکس استاد",
                    ),
                ),
            ],
            options={
                "verbose_name": "professor",
                "verbose_name_plural": "professors",
                "db_table": "professors",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email",), name="unique_professor_email"
                    ),
                    models.UniqueConstraint(
                        fields=("mobile_phone",), name="unique_professor_mobile_phone"
                    ),
                ],
            },
        ),
    ]
