# Generated by Django 5.1.1 on 2024-10-19 20:50

import django.db.models.deletion
import professors.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_name",
                    models.CharField(
                        help_text="The name of the connection",
                        max_length=100,
                        verbose_name="اسم راه ارتباطی",
                    ),
                ),
                ("contact_url", models.URLField(verbose_name="آدرس راه ارتباطی")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "professor contact",
                "verbose_name_plural": "professor contacts",
                "db_table": "professor_contact",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="نام خانوادگی"),
                ),
                (
                    "nation_code",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[professors.validators.NationCodeValidator()],
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "field_of_study",
                    models.CharField(max_length=255, verbose_name="رشته تحصیلی"),
                ),
                (
                    "name_of_education",
                    models.CharField(max_length=255, verbose_name="نام دانشگاه"),
                ),
                (
                    "education_status",
                    models.CharField(
                        choices=[
                            ("دیپلم", "دیپلم"),
                            ("فارغ التحصیل کاردانی", "فارغ التحصیل کاردانی"),
                            ("دانشجوی کارشناسی", "دانشجوی کارشناسی"),
                            ("فارغ التحصیل کارشناسی", "فارغ التحصیل کارشناسی"),
                            ("دانشجوی کارشناسی ارشد", "دانشجوی کارشناسی ارشد"),
                            (
                                "فارغ التحصیل کارشناسی ارشد",
                                "فارغ التحصیل کارشناسی ارشد",
                            ),
                            ("دانشجوی دکترا", "دانشجوی دکترا"),
                            ("فارغ التحصیل دکترا", "فارغ التحصیل دکترا"),
                        ],
                        max_length=26,
                        verbose_name="وضعیت تحصیل",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[users.validators.MobileValidator()],
                        verbose_name="شماره تلفن",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate_image",
                        to="images.image",
                        verbose_name="عکس اخرین مدرک تحصیلی",
                    ),
                ),
                (
                    "professor_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professor_image",
                        to="images.image",
                        verbose_name="عکس استاد",
                    ),
                ),
                (
                    "professor_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact",
                        to="professors.professorcontact",
                        verbose_name="راه ارتباطی استاد",
                    ),
                ),
            ],
            options={
                "verbose_name": "professor",
                "verbose_name_plural": "professors",
                "db_table": "professors",
            },
        ),
    ]
