# Generated by Django 5.1.1 on 2024-10-29 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="professor_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="professor_image",
                to="images.image",
                verbose_name="عکس استاد",
            ),
        ),
    ]
