# Generated by Django 5.1.1 on 2024-11-01 20:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professor",
            options={"verbose_name": "استاد", "verbose_name_plural": "استاید ها"},
        ),
        migrations.AlterField(
            model_name="professor",
            name="mobile_phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=11, verbose_name="شماره تلفن های استاد"
                ),
                blank=True,
                help_text="اگر استاد چندین شماره موبایل رو دارد با کاما از هم جدا کنید",
                null=True,
                size=5,
            ),
        ),
    ]
