# Generated by Django 5.1.1 on 2024-11-09 18:33

import professors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="professor",
            name="unique_professor_email",
        ),
        migrations.RemoveConstraint(
            model_name="professor",
            name="unique_professor_mobile_phone",
        ),
        migrations.AlterField(
            model_name="professor",
            name="nation_code",
            field=models.CharField(
                help_text="کد ملی باید شامل عدد و 11 رقمی باشد و هر کد ملی باید یکتا باشد",
                max_length=10,
                unique=True,
                validators=[professors.validators.NationCodeValidator()],
                verbose_name="کد ملی",
            ),
        ),
    ]
