# Generated by Django 5.0.8 on 2024-09-30 20:46

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professorcontact",
            name="email",
        ),
        migrations.RemoveField(
            model_name="professorcontact",
            name="mobile_phone",
        ),
        migrations.AddField(
            model_name="professor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="mobile_phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[users.validators.MobileValidator()],
                verbose_name="mobile phone",
            ),
        ),
    ]
