# Generated by Django 5.1.1 on 2024-10-22 11:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="professor_contact",
        ),
        migrations.AlterField(
            model_name="professor",
            name="mobile_phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=11, verbose_name="شماره تلفن های استاد"
                ),
                blank=True,
                null=True,
                size=5,
            ),
        ),
    ]
