# Generated by Django 5.0.8 on 2024-09-20 06:30

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0002_alter_professor_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="professorcontact",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
