# Generated by Django 5.0.8 on 2024-09-30 21:56

import django.db.models.deletion
import django_jalali.db.models
import professors.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_created_at_alter_image_updated_at"),
        ("professors", "0002_remove_professorcontact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="birth_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تولد"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificate_image",
                to="images.image",
                verbose_name="عکس اخرین مدرک تحصیلی",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="education_status",
            field=models.CharField(
                choices=[
                    ("دیپلم", "دیپلم"),
                    ("فارغ التحصیل کاردانی", "فارغ التحصیل کاردانی"),
                    ("دانشجوی کارشناسی", "دانشجوی کارشناسی"),
                    ("فارغ التحصیل کارشناسی", "فارغ التحصیل کارشناسی"),
                    ("دانشجوی کارشناسی ارشد", "دانشجوی کارشناسی ارشد"),
                    ("فارغ التحصیل کارشناسی ارشد", "فارغ التحصیل کارشناسی ارشد"),
                    ("دانشجوی دکترا", "دانشجوی دکترا"),
                    ("فارغ التحصیل دکترا", "فارغ التحصیل دکترا"),
                ],
                max_length=26,
                verbose_name="وضعیت تحصیل",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="ایمیل"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="field_of_study",
            field=models.CharField(max_length=255, verbose_name="رشته تحصیلی"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="mobile_phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[users.validators.MobileValidator()],
                verbose_name="شماره تلفن",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="name_of_education",
            field=models.CharField(max_length=255, verbose_name="نام دانشگاه"),
        ),
        migrations.AlterField(
            model_name="professor",
            name="nation_code",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[professors.validators.NationCodeValidator()],
                verbose_name="کد ملی",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="professor_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact",
                to="professors.professorcontact",
                verbose_name="راه ارتباطی استاد",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="professor_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="professor_image",
                to="images.image",
                verbose_name="عکس استاد",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="professorcontact",
            name="contact_name",
            field=models.CharField(
                help_text="The name of the connection",
                max_length=100,
                verbose_name="اسم راه ارتباطی",
            ),
        ),
        migrations.AlterField(
            model_name="professorcontact",
            name="contact_url",
            field=models.URLField(verbose_name="آدرس راه ارتباطی"),
        ),
        migrations.AlterField(
            model_name="professorcontact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="professorcontact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
