# Generated by Django 5.0.8 on 2024-09-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0002_alter_professor_mobile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professorcontact",
            name="contact_name",
            field=models.CharField(
                help_text="The name of the connection",
                max_length=100,
                verbose_name="contact name",
            ),
        ),
        migrations.AlterField(
            model_name="professorcontact",
            name="contact_url",
            field=models.URLField(verbose_name="contact url"),
        ),
    ]
