# Generated by Django 5.0.8 on 2024-09-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0002_professor_professor_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessorContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="contact name"),
                ),
                (
                    "contact_mobile",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="contact mobile"
                    ),
                ),
                (
                    "contact_url",
                    models.URLField(blank=True, null=True, verbose_name="contact url"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "professor contact",
                "verbose_name_plural": "professor contacts",
                "db_table": "professor_contact",
            },
        ),
        migrations.AddField(
            model_name="professor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="professor_contact",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact",
                to="professors.professorcontact",
            ),
            preserve_default=False,
        ),
    ]
