# Generated by Django 5.0.8 on 2024-09-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0003_alter_professor_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
        ),
    ]
