# Generated by Django 5.0.8 on 2024-09-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0003_professorcontact_professor_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professorcontact",
            name="contact_mobile",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="contact mobile"
            ),
        ),
    ]
