# Generated by Django 5.1.1 on 2024-11-10 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "category_name",
                    models.CharField(max_length=50, verbose_name="نام دسته بندی"),
                ),
                (
                    "category_slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="اسلاگ دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
                "db_table": "blog_category",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post_title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="عنوان پست"
                    ),
                ),
                (
                    "tiny_title",
                    models.CharField(
                        blank=True,
                        help_text="عنوان خلاصه شده پست هست و حداکثر 50 تا کاراتر میتوان نوشت",
                        max_length=50,
                        null=True,
                        verbose_name="عنوان کوتاه پست",
                    ),
                ),
                (
                    "introduction",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="مقدمه"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        verbose_name="اسلاگ",
                    ),
                ),
                ("post", models.TextField(verbose_name="متن پست")),
                (
                    "is_publish",
                    models.BooleanField(default=False, verbose_name="قابل انتشار"),
                ),
                (
                    "view_number",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="تعداد بازدید"
                    ),
                ),
                ("post_image", models.ImageField(upload_to="", verbose_name="عکس پست")),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={
                            "is_active": True,
                            "is_staff": True,
                            "is_verified": True,
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="posts",
                        to="blogs.categorynode",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست وبلاگ",
                "verbose_name_plural": "پست های وبلاگ",
                "db_table": "blog_post",
                "ordering": ("-created_at",),
            },
        ),
    ]
