# Generated by Django 5.1.1 on 2024-10-09 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
        ("images", "0003_alter_image_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_image",
        ),
        migrations.AlterField(
            model_name="blogpostimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fk_blog_post_image",
                to="images.image",
                verbose_name="عکس",
            ),
        ),
        migrations.AlterField(
            model_name="blogpostimage",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال بودن"),
        ),
        migrations.AlterField(
            model_name="blogpostimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fk_blog_post",
                to="blogs.post",
                verbose_name="پست",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                limit_choices_to={
                    "is_active": True,
                    "is_staff": True,
                    "is_superuser": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(
                related_name="posts", to="blogs.categorynode", verbose_name="دسته بندی"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="قابل انتشار"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_body",
            field=models.TextField(verbose_name="متن پست"),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_title",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="عنوان پست"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=255, unique=True, verbose_name="اسلاگ"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="view_number",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
    ]
