# Generated by Django 5.1.1 on 2024-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorynode",
            name="category_slug",
            field=models.SlugField(
                allow_unicode=True, max_length=255, verbose_name="اسلاگ دسته بندی"
            ),
        ),
    ]
