# Generated by Django 5.1.1 on 2024-10-19 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                limit_choices_to={
                    "is_active": True,
                    "is_staff": True,
                    "is_verified": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(
                related_name="posts", to="blogs.categorynode", verbose_name="دسته بندی"
            ),
        ),
    ]
