# Generated by Django 5.1.3 on 2025-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_categorynode_created_at_categorynode_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorynode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
