# Generated by Django 5.1.1 on 2024-10-26 15:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_body",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
