# Generated by Django 5.1.1 on 2024-10-10 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_remove_post_post_image_alter_blogpostimage_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorynode",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.RemoveField(
            model_name="categorynode",
            name="depth",
        ),
        migrations.RemoveField(
            model_name="categorynode",
            name="numchild",
        ),
        migrations.RemoveField(
            model_name="categorynode",
            name="path",
        ),
        migrations.AddField(
            model_name="categorynode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="categorynode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="blogs.categorynode",
                verbose_name="دسته بندی والد",
            ),
        ),
        migrations.AlterModelTable(
            name="categorynode",
            table="blog_category",
        ),
    ]
