# Generated by Django 5.1.1 on 2024-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_post_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorynode",
            name="category_name",
            field=models.CharField(max_length=50, verbose_name="نام دسته بندی"),
        ),
        migrations.AlterField(
            model_name="categorynode",
            name="category_slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=255,
                unique=True,
                verbose_name="اسلاگ دسته بندی",
            ),
        ),
    ]
