# Generated by Django 5.1.3 on 2025-02-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_categorynode_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorynode",
            name="category_slug",
        ),
    ]
