# Generated by Django 5.1.1 on 2024-10-31 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_categorynode_category_name_and_more"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "پست وبلاگ",
                "verbose_name_plural": "پست های وبلاگ",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blog_post_image",
                to="images.image",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=255, verbose_name="اسلاگ"
            ),
        ),
    ]
