# Generated by Django 5.1.3 on 2025-02-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_post_deleted_at_post_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "is_staff": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(upload_to="", verbose_name="عکس کاور پست"),
        ),
    ]
