# Generated by Django 5.0.8 on 2024-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        upload_to="images/%Y/%m/%d",
                        width_field="width",
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("focal_point_x", models.PositiveIntegerField(blank=True, null=True)),
                ("focal_point_y", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "focal_point_width",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "focal_point_height",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
