# Generated by Django 5.1.1 on 2024-11-06 13:03

import images.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="عنوانی برای عکس خود انتخاب کنید",
                        max_length=128,
                        verbose_name="عنوان عکس",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        help_text="max size is 5 MG",
                        upload_to="images/%Y/%m/%d",
                        validators=[images.validators.validate_image_size],
                        verbose_name="عکس",
                        width_field="width",
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="عرض اندازه عکس"
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="طول اندازه عکس"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="هش فایل عکس"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="file size as xx.b",
                        null=True,
                        verbose_name="حجم عکس",
                    ),
                ),
                (
                    "image_base64",
                    models.TextField(
                        blank=True, null=True, verbose_name="تبدیل به فورمت base64"
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس",
                "verbose_name_plural": "عکس ها",
                "db_table": "image",
            },
        ),
    ]
