# Generated by Django 5.1.1 on 2024-11-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "عکس", "verbose_name_plural": "عکس ها"},
        ),
    ]
