# Generated by Django 5.0.8 on 2024-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
