# Generated by Django 5.1.1 on 2024-10-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_base64",
            field=models.TextField(
                blank=True, null=True, verbose_name="تبدیل به فورمت base64"
            ),
        ),
    ]
