# Generated by Django 5.1.1 on 2024-11-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_base64",
        ),
    ]
