# Generated by Django 5.0.8 on 2024-09-20 06:30

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
