# Generated by Django 5.0.8 on 2024-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_image_file_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file_hash",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
