# Generated by Django 5.1.1 on 2024-11-01 15:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("professors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="نام محصول")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="درباره دوره"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="قیمت دوره",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="videos/%Y/%m/%d",
                        verbose_name="فیلم معرفی دوره",
                    ),
                ),
                (
                    "sale_number",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="تعداد فروش دوره"
                    ),
                ),
                (
                    "is_sale",
                    models.BooleanField(
                        default=True,
                        help_text="if is sale is true, this course can be sale ,otherwise this course can't",
                        verbose_name="قابل فروش",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=False, verbose_name="دوره رایگان باشد"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="دوره در سایت منتشر شود"
                    ),
                ),
                (
                    "total_like",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="تعداد کاربران پسندیده شده",
                    ),
                ),
                (
                    "number_of_video",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="تعداد ویدیو ها"
                    ),
                ),
                (
                    "course_license",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="لاینسس دوره",
                    ),
                ),
                (
                    "course_level",
                    models.CharField(
                        choices=[
                            ("basic", "مقدماتی"),
                            ("middle", "متوسط"),
                            ("advance", "پیشرفته"),
                        ],
                        default="basic",
                        max_length=7,
                        verbose_name="سطح دوره",
                    ),
                ),
                (
                    "course_status",
                    models.CharField(
                        choices=[
                            ("done", "تمام یافته"),
                            ("in_progress", "در حال برگزاری"),
                        ],
                        default="in_progress",
                        help_text="دروه در حال برگزاری هست یا به اتمام رسیده هست",
                        max_length=11,
                        verbose_name="وضعیت دوره",
                    ),
                ),
                (
                    "course_duration",
                    models.FloatField(
                        default=0.0,
                        editable=False,
                        help_text="تا حالا چند ساعت دوره برگزار شده هست",
                        verbose_name="مدت زمان دوره",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_image",
                        to="images.image",
                        verbose_name="عکس دوره",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professor_course",
                        to="professors.professor",
                        verbose_name="استاد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره",
                "verbose_name_plural": "دوره ها",
                "db_table": "course",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(max_length=2048, verbose_name="متن کامنت")),
                ("public", models.BooleanField(default=True, verbose_name="انتشار")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Enter a score of 1 to 5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(blank=True, null=True, verbose_name="پاسخ ادمین"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_verified": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_comment",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_sale": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_comment",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
                "db_table": "comment",
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="نام دسته بندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=200,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_category",
                        to="images.image",
                        verbose_name="عکس دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی دوره",
                "verbose_name_plural": "دسته بندی دوره ها",
                "db_table": "category",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ManyToManyField(
                related_name="category_course",
                to="courses.coursecategory",
                verbose_name="دسته بندی",
            ),
        ),
        migrations.CreateModel(
            name="DiscountCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("درصدی", "درصدی"), ("مقدار", "مقدار")],
                        default="بدون تخفیف",
                        max_length=10,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                ("value", models.PositiveIntegerField(verbose_name="مقدار تخفیف")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("expired_date", models.DateTimeField(verbose_name="زمان انتقضا")),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={
                            "is_active": True,
                            "is_free": False,
                            "is_sale": True,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_discount",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخفیف",
                "verbose_name_plural": "تخفیف ها",
                "db_table": "discount",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dislike",
                    models.BooleanField(default=False, verbose_name="عدم پسندیدن"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_like",
                        to="courses.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_verified": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_like",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لایک دوره",
                "verbose_name_plural": "لایک های دوره",
                "db_table": "like",
                "unique_together": {("user", "course")},
            },
        ),
    ]
