# Generated by Django 5.1.1 on 2024-11-09 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_duration",
        ),
        migrations.AlterField(
            model_name="course",
            name="course_license",
            field=models.TextField(
                blank=True,
                help_text="هر دوره درون اسپات پلییر یک لاینسس دارد یا همان شناسه دوره",
                null=True,
                verbose_name="لاینسس دوره",
            ),
        ),
        migrations.AlterField(
            model_name="discountcourse",
            name="course",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_discount",
                to="courses.course",
                verbose_name="دوره",
            ),
        ),
    ]
