# Generated by Django 5.0.8 on 2024-09-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_alter_course_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursecategory",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_icon/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="courses.coursecategory",
            ),
        ),
    ]
