# Generated by Django 5.1.1 on 2024-11-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_course_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_free",
            field=models.BooleanField(
                default=False,
                help_text="دروه رایگان در نظر گرفته خواهد شد",
                verbose_name="دوره رایگان باشد",
            ),
        ),
    ]
