# Generated by Django 5.1.1 on 2024-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=200,
                unique=True,
                verbose_name="اسلاگ",
            ),
        ),
    ]
