# Generated by Django 5.0.8 on 2024-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="sales",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
