# Generated by Django 5.0.8 on 2024-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_coursecategory_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
