# Generated by Django 5.0.8 on 2024-09-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_comment_admin_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcourse",
            name="expired_date",
            field=models.DateTimeField(),
        ),
    ]
