# Generated by Django 5.0.8 on 2024-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_rename_sales_course_sale_number_course_is_free_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="is_sale",
            field=models.BooleanField(
                default=True,
                help_text="if is sale is true, this course can be sale ,otherwise this course can't",
            ),
        ),
    ]
