# Generated by Django 5.0.8 on 2024-09-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_coursecategory_options_course_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="desc",
            new_name="description",
        ),
    ]
