# Generated by Django 5.0.8 on 2024-09-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_coursecategory_slug_alter_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="admin_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
    ]
