# Generated by Django 5.0.8 on 2024-09-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_options_course_is_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcourse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="discountcourse",
            name="discount_type",
            field=models.CharField(
                choices=[("درصدی", "درصدی"), ("مقدار", "مقدار")],
                default="بدون تخفیف",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="discountcourse",
            name="expired_date",
            field=models.DateTimeField(),
        ),
    ]
