# Generated by Django 5.0.8 on 2024-09-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_coursecategory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="user",
        ),
    ]
