# Generated by Django 5.0.8 on 2024-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_comment_admin_response_alter_coursecategory_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ManyToManyField(
                related_name="category_course", to="courses.coursecategory"
            ),
        ),
    ]
