# Generated by Django 5.0.8 on 2024-09-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reply_comment",
                to="courses.comment",
            ),
        ),
    ]
