# Generated by Django 5.0.8 on 2024-09-08 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_comment_reply_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discountcourse",
            options={"verbose_name": "discount", "verbose_name_plural": "discounts"},
        ),
        migrations.RenameField(
            model_name="discountcourse",
            old_name="type",
            new_name="discount_type",
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "is_verified": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="discountcourse",
            table="discount",
        ),
    ]
