# Generated by Django 5.0.8 on 2024-09-09 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_course_price_alter_discountcourse_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcourse",
            name="course",
            field=models.OneToOneField(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_discount",
                to="courses.course",
            ),
        ),
    ]
