# Generated by Django 5.0.8 on 2024-09-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_discountcourse_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_comment",
                to="courses.comment",
            ),
        ),
        migrations.AlterField(
            model_name="discountcourse",
            name="course",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_discount",
                to="courses.course",
            ),
        ),
    ]
