# Generated by Django 5.0.8 on 2024-09-11 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_comment_reply_to_alter_discountcourse_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="reply_to",
        ),
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
