# Generated by Django 5.0.8 on 2024-09-11 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_remove_comment_reply_to_comment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecategory",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Enter a score of 1 to 5",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
