# Generated by Django 5.1.3 on 2024-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("complete", "complete"),
                    ("pending", "pending"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
