# Generated by Django 5.0.8 on 2024-09-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_cart_cart_complete_cart_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cart_complete",
        ),
    ]
